### PR TITLE
Remove stale repos

### PR DESCRIPTION
**Pull request by jcrosby**
Hello @valueof, 

Please review the following commits I made in branch 'jcrosby-cleanup'.

83b71d8be076c5469b4df4f8fd1bec5d2d0a6312 (2015-07-13 15:00:40 -0700)
Remove bidar

R=@valueof

Test plan: 'not tested'

### CODE REVIEW

**Comment by valueof** [comment]
Should we make those repos private?

**Comment by jcrosby** [comment]
I would vote yes unless there are known users that would like to become the new maintainers. I didn't see any of these when looking around.

**Comment by valueof** [comment]
Yeah, nobody filed an issue for over two years—unlikely there are any users.

**Comment by valueof** [comment]
Okay, I made them private. LGTM

**Pull request merged**
